### ISSUE TITLE
Drone: Can't Connect Without Private SSH Key

### ISSUE THREAD

**Issue by parrotmac** [drone-plugins/drone-ssh#18]
Relevant section of my .drone.yml
```deploy:
  ssh:
    image: plugins/ssh
    host: example.com
    user: isaac
    port: 22
    script:
      - echo `date` > test.txt
```

Drone Outputs this:
```
$ docker images -q -f dangling=true
[info] Pulling image plugins/ssh:latest
Error: Can't connect without a private SSH key.
[info] build failed (exit code 1)
```

I've copy-pasted the Public Key that shows under the Settings tab into my ~/.authorized_keys on my host machine, and it really _looks_ like there are private keys in the /var/lib/drone/drone.sqlite database.

**Comment by Bugagazavr** [comment]
Did you set your private key?

```sh
drone secret add --image=plugins/ssh your/repo_name PLUGIN_SSH_KEY $(cat ~/.ssh/id_rsa.pub)
```

**Comment by tboerger** [comment]
It sounds like you try to use the 0.5 plugin on a 0.4 server. The 0.5 server doesn't provide any ssh key.

**Comment by parrotmac** [comment]
Is there any way to use the 0.4 plugin? Tagging :0.4 fails

**Comment by tboerger** [comment]
plugins/drone-docker is 0.4, plugins/docker is 0.5 :)

**Comment by parrotmac** [comment]
@tboerger I probably wasn't very clear :) Is there a way to use the equivalent of `plugins/ssh:0.4` since I'm using a 0.4 server?

**Comment by tboerger** [comment]
Just use `plugins/drone-ssh`, for 0.4 we had the convention to name the images `plugins/drone-foo` while it have been changed for 0.5 to `plugins/foo`. All plugins should have a `release/0.4` branch and for this plugin you can see the docs at https://github.com/drone-plugins/drone-ssh/blob/release/0.4/DOCS.md

I will close this issue since it's just mixing 0.5 plugins with a 0.4 server. If you still encounter problems feel free to join the Gitter chat and ask there for support.
